// @ts-nocheck
import * as __fd_glob_77 from "../content/docs/vi/windows/tweaks/sophia.mdx?collection=docs"
import * as __fd_glob_76 from "../content/docs/vi/windows/tweaks/index.mdx?collection=docs"
import * as __fd_glob_75 from "../content/docs/vi/windows/tweaks/atlas-os.mdx?collection=docs"
import * as __fd_glob_74 from "../content/docs/vi/aosp-development/kernel-old/packaging.mdx?collection=docs"
import * as __fd_glob_73 from "../content/docs/vi/aosp-development/kernel-old/index.mdx?collection=docs"
import * as __fd_glob_72 from "../content/docs/vi/aosp-development/kernel-old/dependency.mdx?collection=docs"
import * as __fd_glob_71 from "../content/docs/vi/aosp-development/kernel-old/building-repo.mdx?collection=docs"
import * as __fd_glob_70 from "../content/docs/vi/aosp-development/kernel-old/building-manual.mdx?collection=docs"
import * as __fd_glob_69 from "../content/docs/vi/aosp-development/kernel-old/bootable-image-legacy.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/vi/android-rooting/play-integrity/playstrong.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/vi/android-rooting/play-integrity/modules.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/vi/android-rooting/play-integrity/index.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/vi/android-rooting/root-hiding-again/play-integrity.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/vi/android-rooting/root-hiding-again/kernelsu-3.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/vi/android-rooting/root-hiding-again/introduction.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/vi/android-rooting/root-hiding-again/index.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/vi/android-rooting/root-hiding-again/app-hiding.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/en/windows/tweaks/sophia.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/en/windows/tweaks/index.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/en/windows/tweaks/atlas-os.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/en/aosp-development/kernel-old/packaging.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/en/aosp-development/kernel-old/index.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/en/aosp-development/kernel-old/dependency.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/en/aosp-development/kernel-old/building-repo.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/en/aosp-development/kernel-old/building-manual.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/en/aosp-development/kernel-old/bootable-image-legacy.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/en/android-rooting/root-hiding-again/play-integrity.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/en/android-rooting/root-hiding-again/kernelsu-3.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/en/android-rooting/root-hiding-again/introduction.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/en/android-rooting/root-hiding-again/index.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/en/android-rooting/root-hiding-again/app-hiding.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/en/android-rooting/play-integrity/playstrong.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/en/android-rooting/play-integrity/modules.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/en/android-rooting/play-integrity/index.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/vi/windows/index.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/vi/windows/general.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/vi/aosp-development/intro.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/vi/aosp-development/index.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/vi/android-rooting/root-hiding.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/vi/android-rooting/lineage.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/vi/android-rooting/intro.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/vi/android-rooting/index.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/en/windows/index.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/en/windows/general.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/en/aosp-development/intro.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/en/aosp-development/index.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/en/android-rooting/root-hiding.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/en/android-rooting/lineage.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/en/android-rooting/intro.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/en/android-rooting/index.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/vi/intro.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/vi/index.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/en/intro.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/en/index.mdx?collection=docs"
import { default as __fd_glob_23 } from "../content/docs/en/windows/tweaks/meta.json?collection=docs"
import { default as __fd_glob_22 } from "../content/docs/en/android-rooting/play-integrity/meta.json?collection=docs"
import { default as __fd_glob_21 } from "../content/docs/en/android-rooting/root-hiding-again/meta.json?collection=docs"
import { default as __fd_glob_20 } from "../content/docs/en/aosp-development/kernel-old/meta.json?collection=docs"
import { default as __fd_glob_19 } from "../content/docs/vi/windows/tweaks/meta.json?collection=docs"
import { default as __fd_glob_18 } from "../content/docs/vi/android-rooting/root-hiding-again/meta.json?collection=docs"
import { default as __fd_glob_17 } from "../content/docs/vi/android-rooting/play-integrity/meta.json?collection=docs"
import { default as __fd_glob_16 } from "../content/docs/vi/aosp-development/kernel-old/meta.json?collection=docs"
import { default as __fd_glob_15 } from "../content/docs/en/windows/meta.json?collection=docs"
import { default as __fd_glob_14 } from "../content/docs/en/android-rooting/meta.json?collection=docs"
import { default as __fd_glob_13 } from "../content/docs/en/aosp-development/meta.json?collection=docs"
import { default as __fd_glob_12 } from "../content/docs/vi/windows/meta.json?collection=docs"
import { default as __fd_glob_11 } from "../content/docs/vi/android-rooting/meta.json?collection=docs"
import { default as __fd_glob_10 } from "../content/docs/vi/aosp-development/meta.json?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/en/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/vi/meta.json?collection=docs"
import * as __fd_glob_7 from "../content/blog/vi/welcome/index.mdx?collection=blog"
import * as __fd_glob_6 from "../content/blog/en/welcome/index.mdx?collection=blog"
import * as __fd_glob_5 from "../content/blog/vi/mdx-blog-post.mdx?collection=blog"
import * as __fd_glob_4 from "../content/blog/vi/long-blog-post.mdx?collection=blog"
import * as __fd_glob_3 from "../content/blog/vi/first-blog-post.mdx?collection=blog"
import * as __fd_glob_2 from "../content/blog/en/mdx-blog-post.mdx?collection=blog"
import * as __fd_glob_1 from "../content/blog/en/long-blog-post.mdx?collection=blog"
import * as __fd_glob_0 from "../content/blog/en/first-blog-post.mdx?collection=blog"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const blog = await create.doc("blog", "content/blog", {"en/first-blog-post.mdx": __fd_glob_0, "en/long-blog-post.mdx": __fd_glob_1, "en/mdx-blog-post.mdx": __fd_glob_2, "vi/first-blog-post.mdx": __fd_glob_3, "vi/long-blog-post.mdx": __fd_glob_4, "vi/mdx-blog-post.mdx": __fd_glob_5, "en/welcome/index.mdx": __fd_glob_6, "vi/welcome/index.mdx": __fd_glob_7, });

export const docs = await create.docs("docs", "content/docs", {"vi/meta.json": __fd_glob_8, "en/meta.json": __fd_glob_9, "vi/aosp-development/meta.json": __fd_glob_10, "vi/android-rooting/meta.json": __fd_glob_11, "vi/windows/meta.json": __fd_glob_12, "en/aosp-development/meta.json": __fd_glob_13, "en/android-rooting/meta.json": __fd_glob_14, "en/windows/meta.json": __fd_glob_15, "vi/aosp-development/kernel-old/meta.json": __fd_glob_16, "vi/android-rooting/play-integrity/meta.json": __fd_glob_17, "vi/android-rooting/root-hiding-again/meta.json": __fd_glob_18, "vi/windows/tweaks/meta.json": __fd_glob_19, "en/aosp-development/kernel-old/meta.json": __fd_glob_20, "en/android-rooting/root-hiding-again/meta.json": __fd_glob_21, "en/android-rooting/play-integrity/meta.json": __fd_glob_22, "en/windows/tweaks/meta.json": __fd_glob_23, }, {"en/index.mdx": __fd_glob_24, "en/intro.mdx": __fd_glob_25, "vi/index.mdx": __fd_glob_26, "vi/intro.mdx": __fd_glob_27, "en/android-rooting/index.mdx": __fd_glob_28, "en/android-rooting/intro.mdx": __fd_glob_29, "en/android-rooting/lineage.mdx": __fd_glob_30, "en/android-rooting/root-hiding.mdx": __fd_glob_31, "en/aosp-development/index.mdx": __fd_glob_32, "en/aosp-development/intro.mdx": __fd_glob_33, "en/windows/general.mdx": __fd_glob_34, "en/windows/index.mdx": __fd_glob_35, "vi/android-rooting/index.mdx": __fd_glob_36, "vi/android-rooting/intro.mdx": __fd_glob_37, "vi/android-rooting/lineage.mdx": __fd_glob_38, "vi/android-rooting/root-hiding.mdx": __fd_glob_39, "vi/aosp-development/index.mdx": __fd_glob_40, "vi/aosp-development/intro.mdx": __fd_glob_41, "vi/windows/general.mdx": __fd_glob_42, "vi/windows/index.mdx": __fd_glob_43, "en/android-rooting/play-integrity/index.mdx": __fd_glob_44, "en/android-rooting/play-integrity/modules.mdx": __fd_glob_45, "en/android-rooting/play-integrity/playstrong.mdx": __fd_glob_46, "en/android-rooting/root-hiding-again/app-hiding.mdx": __fd_glob_47, "en/android-rooting/root-hiding-again/index.mdx": __fd_glob_48, "en/android-rooting/root-hiding-again/introduction.mdx": __fd_glob_49, "en/android-rooting/root-hiding-again/kernelsu-3.mdx": __fd_glob_50, "en/android-rooting/root-hiding-again/play-integrity.mdx": __fd_glob_51, "en/aosp-development/kernel-old/bootable-image-legacy.mdx": __fd_glob_52, "en/aosp-development/kernel-old/building-manual.mdx": __fd_glob_53, "en/aosp-development/kernel-old/building-repo.mdx": __fd_glob_54, "en/aosp-development/kernel-old/dependency.mdx": __fd_glob_55, "en/aosp-development/kernel-old/index.mdx": __fd_glob_56, "en/aosp-development/kernel-old/packaging.mdx": __fd_glob_57, "en/windows/tweaks/atlas-os.mdx": __fd_glob_58, "en/windows/tweaks/index.mdx": __fd_glob_59, "en/windows/tweaks/sophia.mdx": __fd_glob_60, "vi/android-rooting/root-hiding-again/app-hiding.mdx": __fd_glob_61, "vi/android-rooting/root-hiding-again/index.mdx": __fd_glob_62, "vi/android-rooting/root-hiding-again/introduction.mdx": __fd_glob_63, "vi/android-rooting/root-hiding-again/kernelsu-3.mdx": __fd_glob_64, "vi/android-rooting/root-hiding-again/play-integrity.mdx": __fd_glob_65, "vi/android-rooting/play-integrity/index.mdx": __fd_glob_66, "vi/android-rooting/play-integrity/modules.mdx": __fd_glob_67, "vi/android-rooting/play-integrity/playstrong.mdx": __fd_glob_68, "vi/aosp-development/kernel-old/bootable-image-legacy.mdx": __fd_glob_69, "vi/aosp-development/kernel-old/building-manual.mdx": __fd_glob_70, "vi/aosp-development/kernel-old/building-repo.mdx": __fd_glob_71, "vi/aosp-development/kernel-old/dependency.mdx": __fd_glob_72, "vi/aosp-development/kernel-old/index.mdx": __fd_glob_73, "vi/aosp-development/kernel-old/packaging.mdx": __fd_glob_74, "vi/windows/tweaks/atlas-os.mdx": __fd_glob_75, "vi/windows/tweaks/index.mdx": __fd_glob_76, "vi/windows/tweaks/sophia.mdx": __fd_glob_77, });